// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
#pragma warning disable 1591, 3008, 3009
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public static partial class MVC
{
    public static BackOffice.Web.Controllers.BaseController Base = new BackOffice.Web.Controllers.T4MVC_BaseController();
    public static BackOffice.Web.Controllers.HomeController Home = new BackOffice.Web.Controllers.T4MVC_HomeController();
    public static BackOffice.Web.Controllers.ProviderController Provider = new BackOffice.Web.Controllers.T4MVC_ProviderController();
    public static T4MVC.SharedController Shared = new T4MVC.SharedController();
}

namespace T4MVC
{
}

namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class Dummy
    {
        private Dummy() { }
        public static Dummy Instance = new Dummy();
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_ActionResult : System.Web.Mvc.ActionResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ActionResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    public override void ExecuteResult(System.Web.Mvc.ControllerContext context) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}



namespace Links
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Scripts {
        private const string URLPATH = "~/Scripts";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        public static readonly string _references_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/_references.min.js") ? Url("_references.min.js") : Url("_references.js");
        public static readonly string bootstrap_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap.min.js") ? Url("bootstrap.min.js") : Url("bootstrap.js");
        public static readonly string bootstrap_min_js = Url("bootstrap.min.js");
        public static readonly string jquery_2_1_1_intellisense_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-2.1.1.intellisense.min.js") ? Url("jquery-2.1.1.intellisense.min.js") : Url("jquery-2.1.1.intellisense.js");
        public static readonly string jquery_2_1_1_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-2.1.1.min.js") ? Url("jquery-2.1.1.min.js") : Url("jquery-2.1.1.js");
        public static readonly string jquery_2_1_1_min_js = Url("jquery-2.1.1.min.js");
        public static readonly string jquery_2_1_1_min_map = Url("jquery-2.1.1.min.map");
        public static readonly string jquery_ui_1_11_2_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-ui-1.11.2.min.js") ? Url("jquery-ui-1.11.2.min.js") : Url("jquery-ui-1.11.2.js");
        public static readonly string jquery_ui_1_11_2_min_js = Url("jquery-ui-1.11.2.min.js");
        public static readonly string jquery_validate_vsdoc_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate-vsdoc.min.js") ? Url("jquery.validate-vsdoc.min.js") : Url("jquery.validate-vsdoc.js");
        public static readonly string jquery_validate_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate.min.js") ? Url("jquery.validate.min.js") : Url("jquery.validate.js");
        public static readonly string jquery_validate_min_js = Url("jquery.validate.min.js");
        public static readonly string jquery_validate_unobtrusive_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate.unobtrusive.min.js") ? Url("jquery.validate.unobtrusive.min.js") : Url("jquery.validate.unobtrusive.js");
        public static readonly string jquery_validate_unobtrusive_min_js = Url("jquery.validate.unobtrusive.min.js");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class kendo {
            private const string URLPATH = "~/Scripts/kendo";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class _2014_1_318 {
                private const string URLPATH = "~/Scripts/kendo/2014.1.318";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class cultures {
                    private const string URLPATH = "~/Scripts/kendo/2014.1.318/cultures";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string kendo_culture_af_ZA_min_js = Url("kendo.culture.af-ZA.min.js");
                    public static readonly string kendo_culture_af_min_js = Url("kendo.culture.af.min.js");
                    public static readonly string kendo_culture_am_ET_min_js = Url("kendo.culture.am-ET.min.js");
                    public static readonly string kendo_culture_am_min_js = Url("kendo.culture.am.min.js");
                    public static readonly string kendo_culture_ar_AE_min_js = Url("kendo.culture.ar-AE.min.js");
                    public static readonly string kendo_culture_ar_BH_min_js = Url("kendo.culture.ar-BH.min.js");
                    public static readonly string kendo_culture_ar_DZ_min_js = Url("kendo.culture.ar-DZ.min.js");
                    public static readonly string kendo_culture_ar_EG_min_js = Url("kendo.culture.ar-EG.min.js");
                    public static readonly string kendo_culture_ar_IQ_min_js = Url("kendo.culture.ar-IQ.min.js");
                    public static readonly string kendo_culture_ar_JO_min_js = Url("kendo.culture.ar-JO.min.js");
                    public static readonly string kendo_culture_ar_KW_min_js = Url("kendo.culture.ar-KW.min.js");
                    public static readonly string kendo_culture_ar_LB_min_js = Url("kendo.culture.ar-LB.min.js");
                    public static readonly string kendo_culture_ar_LY_min_js = Url("kendo.culture.ar-LY.min.js");
                    public static readonly string kendo_culture_ar_MA_min_js = Url("kendo.culture.ar-MA.min.js");
                    public static readonly string kendo_culture_ar_OM_min_js = Url("kendo.culture.ar-OM.min.js");
                    public static readonly string kendo_culture_ar_QA_min_js = Url("kendo.culture.ar-QA.min.js");
                    public static readonly string kendo_culture_ar_SA_min_js = Url("kendo.culture.ar-SA.min.js");
                    public static readonly string kendo_culture_ar_SY_min_js = Url("kendo.culture.ar-SY.min.js");
                    public static readonly string kendo_culture_ar_TN_min_js = Url("kendo.culture.ar-TN.min.js");
                    public static readonly string kendo_culture_ar_YE_min_js = Url("kendo.culture.ar-YE.min.js");
                    public static readonly string kendo_culture_ar_min_js = Url("kendo.culture.ar.min.js");
                    public static readonly string kendo_culture_arn_CL_min_js = Url("kendo.culture.arn-CL.min.js");
                    public static readonly string kendo_culture_arn_min_js = Url("kendo.culture.arn.min.js");
                    public static readonly string kendo_culture_as_IN_min_js = Url("kendo.culture.as-IN.min.js");
                    public static readonly string kendo_culture_as_min_js = Url("kendo.culture.as.min.js");
                    public static readonly string kendo_culture_az_Cyrl_AZ_min_js = Url("kendo.culture.az-Cyrl-AZ.min.js");
                    public static readonly string kendo_culture_az_Cyrl_min_js = Url("kendo.culture.az-Cyrl.min.js");
                    public static readonly string kendo_culture_az_Latn_AZ_min_js = Url("kendo.culture.az-Latn-AZ.min.js");
                    public static readonly string kendo_culture_az_Latn_min_js = Url("kendo.culture.az-Latn.min.js");
                    public static readonly string kendo_culture_az_min_js = Url("kendo.culture.az.min.js");
                    public static readonly string kendo_culture_ba_RU_min_js = Url("kendo.culture.ba-RU.min.js");
                    public static readonly string kendo_culture_ba_min_js = Url("kendo.culture.ba.min.js");
                    public static readonly string kendo_culture_be_BY_min_js = Url("kendo.culture.be-BY.min.js");
                    public static readonly string kendo_culture_be_min_js = Url("kendo.culture.be.min.js");
                    public static readonly string kendo_culture_bg_BG_min_js = Url("kendo.culture.bg-BG.min.js");
                    public static readonly string kendo_culture_bg_min_js = Url("kendo.culture.bg.min.js");
                    public static readonly string kendo_culture_bn_BD_min_js = Url("kendo.culture.bn-BD.min.js");
                    public static readonly string kendo_culture_bn_IN_min_js = Url("kendo.culture.bn-IN.min.js");
                    public static readonly string kendo_culture_bn_min_js = Url("kendo.culture.bn.min.js");
                    public static readonly string kendo_culture_bo_CN_min_js = Url("kendo.culture.bo-CN.min.js");
                    public static readonly string kendo_culture_bo_min_js = Url("kendo.culture.bo.min.js");
                    public static readonly string kendo_culture_br_FR_min_js = Url("kendo.culture.br-FR.min.js");
                    public static readonly string kendo_culture_br_min_js = Url("kendo.culture.br.min.js");
                    public static readonly string kendo_culture_bs_Cyrl_BA_min_js = Url("kendo.culture.bs-Cyrl-BA.min.js");
                    public static readonly string kendo_culture_bs_Cyrl_min_js = Url("kendo.culture.bs-Cyrl.min.js");
                    public static readonly string kendo_culture_bs_Latn_BA_min_js = Url("kendo.culture.bs-Latn-BA.min.js");
                    public static readonly string kendo_culture_bs_Latn_min_js = Url("kendo.culture.bs-Latn.min.js");
                    public static readonly string kendo_culture_bs_min_js = Url("kendo.culture.bs.min.js");
                    public static readonly string kendo_culture_ca_ES_min_js = Url("kendo.culture.ca-ES.min.js");
                    public static readonly string kendo_culture_ca_min_js = Url("kendo.culture.ca.min.js");
                    public static readonly string kendo_culture_co_FR_min_js = Url("kendo.culture.co-FR.min.js");
                    public static readonly string kendo_culture_co_min_js = Url("kendo.culture.co.min.js");
                    public static readonly string kendo_culture_cs_CZ_min_js = Url("kendo.culture.cs-CZ.min.js");
                    public static readonly string kendo_culture_cs_min_js = Url("kendo.culture.cs.min.js");
                    public static readonly string kendo_culture_cy_GB_min_js = Url("kendo.culture.cy-GB.min.js");
                    public static readonly string kendo_culture_cy_min_js = Url("kendo.culture.cy.min.js");
                    public static readonly string kendo_culture_da_DK_min_js = Url("kendo.culture.da-DK.min.js");
                    public static readonly string kendo_culture_da_min_js = Url("kendo.culture.da.min.js");
                    public static readonly string kendo_culture_de_AT_min_js = Url("kendo.culture.de-AT.min.js");
                    public static readonly string kendo_culture_de_CH_min_js = Url("kendo.culture.de-CH.min.js");
                    public static readonly string kendo_culture_de_DE_min_js = Url("kendo.culture.de-DE.min.js");
                    public static readonly string kendo_culture_de_LI_min_js = Url("kendo.culture.de-LI.min.js");
                    public static readonly string kendo_culture_de_LU_min_js = Url("kendo.culture.de-LU.min.js");
                    public static readonly string kendo_culture_de_min_js = Url("kendo.culture.de.min.js");
                    public static readonly string kendo_culture_dsb_DE_min_js = Url("kendo.culture.dsb-DE.min.js");
                    public static readonly string kendo_culture_dsb_min_js = Url("kendo.culture.dsb.min.js");
                    public static readonly string kendo_culture_dv_MV_min_js = Url("kendo.culture.dv-MV.min.js");
                    public static readonly string kendo_culture_dv_min_js = Url("kendo.culture.dv.min.js");
                    public static readonly string kendo_culture_el_GR_min_js = Url("kendo.culture.el-GR.min.js");
                    public static readonly string kendo_culture_el_min_js = Url("kendo.culture.el.min.js");
                    public static readonly string kendo_culture_en_029_min_js = Url("kendo.culture.en-029.min.js");
                    public static readonly string kendo_culture_en_AU_min_js = Url("kendo.culture.en-AU.min.js");
                    public static readonly string kendo_culture_en_BZ_min_js = Url("kendo.culture.en-BZ.min.js");
                    public static readonly string kendo_culture_en_CA_min_js = Url("kendo.culture.en-CA.min.js");
                    public static readonly string kendo_culture_en_GB_min_js = Url("kendo.culture.en-GB.min.js");
                    public static readonly string kendo_culture_en_IE_min_js = Url("kendo.culture.en-IE.min.js");
                    public static readonly string kendo_culture_en_IN_min_js = Url("kendo.culture.en-IN.min.js");
                    public static readonly string kendo_culture_en_JM_min_js = Url("kendo.culture.en-JM.min.js");
                    public static readonly string kendo_culture_en_MY_min_js = Url("kendo.culture.en-MY.min.js");
                    public static readonly string kendo_culture_en_NZ_min_js = Url("kendo.culture.en-NZ.min.js");
                    public static readonly string kendo_culture_en_PH_min_js = Url("kendo.culture.en-PH.min.js");
                    public static readonly string kendo_culture_en_SG_min_js = Url("kendo.culture.en-SG.min.js");
                    public static readonly string kendo_culture_en_TT_min_js = Url("kendo.culture.en-TT.min.js");
                    public static readonly string kendo_culture_en_US_min_js = Url("kendo.culture.en-US.min.js");
                    public static readonly string kendo_culture_en_ZA_min_js = Url("kendo.culture.en-ZA.min.js");
                    public static readonly string kendo_culture_en_ZW_min_js = Url("kendo.culture.en-ZW.min.js");
                    public static readonly string kendo_culture_en_min_js = Url("kendo.culture.en.min.js");
                    public static readonly string kendo_culture_es_AR_min_js = Url("kendo.culture.es-AR.min.js");
                    public static readonly string kendo_culture_es_BO_min_js = Url("kendo.culture.es-BO.min.js");
                    public static readonly string kendo_culture_es_CL_min_js = Url("kendo.culture.es-CL.min.js");
                    public static readonly string kendo_culture_es_CO_min_js = Url("kendo.culture.es-CO.min.js");
                    public static readonly string kendo_culture_es_CR_min_js = Url("kendo.culture.es-CR.min.js");
                    public static readonly string kendo_culture_es_DO_min_js = Url("kendo.culture.es-DO.min.js");
                    public static readonly string kendo_culture_es_EC_min_js = Url("kendo.culture.es-EC.min.js");
                    public static readonly string kendo_culture_es_ES_min_js = Url("kendo.culture.es-ES.min.js");
                    public static readonly string kendo_culture_es_GT_min_js = Url("kendo.culture.es-GT.min.js");
                    public static readonly string kendo_culture_es_HN_min_js = Url("kendo.culture.es-HN.min.js");
                    public static readonly string kendo_culture_es_MX_min_js = Url("kendo.culture.es-MX.min.js");
                    public static readonly string kendo_culture_es_NI_min_js = Url("kendo.culture.es-NI.min.js");
                    public static readonly string kendo_culture_es_PA_min_js = Url("kendo.culture.es-PA.min.js");
                    public static readonly string kendo_culture_es_PE_min_js = Url("kendo.culture.es-PE.min.js");
                    public static readonly string kendo_culture_es_PR_min_js = Url("kendo.culture.es-PR.min.js");
                    public static readonly string kendo_culture_es_PY_min_js = Url("kendo.culture.es-PY.min.js");
                    public static readonly string kendo_culture_es_SV_min_js = Url("kendo.culture.es-SV.min.js");
                    public static readonly string kendo_culture_es_US_min_js = Url("kendo.culture.es-US.min.js");
                    public static readonly string kendo_culture_es_UY_min_js = Url("kendo.culture.es-UY.min.js");
                    public static readonly string kendo_culture_es_VE_min_js = Url("kendo.culture.es-VE.min.js");
                    public static readonly string kendo_culture_es_min_js = Url("kendo.culture.es.min.js");
                    public static readonly string kendo_culture_et_EE_min_js = Url("kendo.culture.et-EE.min.js");
                    public static readonly string kendo_culture_et_min_js = Url("kendo.culture.et.min.js");
                    public static readonly string kendo_culture_eu_ES_min_js = Url("kendo.culture.eu-ES.min.js");
                    public static readonly string kendo_culture_eu_min_js = Url("kendo.culture.eu.min.js");
                    public static readonly string kendo_culture_fa_IR_min_js = Url("kendo.culture.fa-IR.min.js");
                    public static readonly string kendo_culture_fa_min_js = Url("kendo.culture.fa.min.js");
                    public static readonly string kendo_culture_fi_FI_min_js = Url("kendo.culture.fi-FI.min.js");
                    public static readonly string kendo_culture_fi_min_js = Url("kendo.culture.fi.min.js");
                    public static readonly string kendo_culture_fil_PH_min_js = Url("kendo.culture.fil-PH.min.js");
                    public static readonly string kendo_culture_fil_min_js = Url("kendo.culture.fil.min.js");
                    public static readonly string kendo_culture_fo_FO_min_js = Url("kendo.culture.fo-FO.min.js");
                    public static readonly string kendo_culture_fo_min_js = Url("kendo.culture.fo.min.js");
                    public static readonly string kendo_culture_fr_BE_min_js = Url("kendo.culture.fr-BE.min.js");
                    public static readonly string kendo_culture_fr_CA_min_js = Url("kendo.culture.fr-CA.min.js");
                    public static readonly string kendo_culture_fr_CH_min_js = Url("kendo.culture.fr-CH.min.js");
                    public static readonly string kendo_culture_fr_FR_min_js = Url("kendo.culture.fr-FR.min.js");
                    public static readonly string kendo_culture_fr_LU_min_js = Url("kendo.culture.fr-LU.min.js");
                    public static readonly string kendo_culture_fr_MC_min_js = Url("kendo.culture.fr-MC.min.js");
                    public static readonly string kendo_culture_fr_min_js = Url("kendo.culture.fr.min.js");
                    public static readonly string kendo_culture_fy_NL_min_js = Url("kendo.culture.fy-NL.min.js");
                    public static readonly string kendo_culture_fy_min_js = Url("kendo.culture.fy.min.js");
                    public static readonly string kendo_culture_ga_IE_min_js = Url("kendo.culture.ga-IE.min.js");
                    public static readonly string kendo_culture_ga_min_js = Url("kendo.culture.ga.min.js");
                    public static readonly string kendo_culture_gd_GB_min_js = Url("kendo.culture.gd-GB.min.js");
                    public static readonly string kendo_culture_gd_min_js = Url("kendo.culture.gd.min.js");
                    public static readonly string kendo_culture_gl_ES_min_js = Url("kendo.culture.gl-ES.min.js");
                    public static readonly string kendo_culture_gl_min_js = Url("kendo.culture.gl.min.js");
                    public static readonly string kendo_culture_gsw_FR_min_js = Url("kendo.culture.gsw-FR.min.js");
                    public static readonly string kendo_culture_gsw_min_js = Url("kendo.culture.gsw.min.js");
                    public static readonly string kendo_culture_gu_IN_min_js = Url("kendo.culture.gu-IN.min.js");
                    public static readonly string kendo_culture_gu_min_js = Url("kendo.culture.gu.min.js");
                    public static readonly string kendo_culture_ha_Latn_NG_min_js = Url("kendo.culture.ha-Latn-NG.min.js");
                    public static readonly string kendo_culture_ha_Latn_min_js = Url("kendo.culture.ha-Latn.min.js");
                    public static readonly string kendo_culture_ha_min_js = Url("kendo.culture.ha.min.js");
                    public static readonly string kendo_culture_he_IL_min_js = Url("kendo.culture.he-IL.min.js");
                    public static readonly string kendo_culture_he_min_js = Url("kendo.culture.he.min.js");
                    public static readonly string kendo_culture_hi_IN_min_js = Url("kendo.culture.hi-IN.min.js");
                    public static readonly string kendo_culture_hi_min_js = Url("kendo.culture.hi.min.js");
                    public static readonly string kendo_culture_hr_BA_min_js = Url("kendo.culture.hr-BA.min.js");
                    public static readonly string kendo_culture_hr_HR_min_js = Url("kendo.culture.hr-HR.min.js");
                    public static readonly string kendo_culture_hr_min_js = Url("kendo.culture.hr.min.js");
                    public static readonly string kendo_culture_hsb_DE_min_js = Url("kendo.culture.hsb-DE.min.js");
                    public static readonly string kendo_culture_hsb_min_js = Url("kendo.culture.hsb.min.js");
                    public static readonly string kendo_culture_hu_HU_min_js = Url("kendo.culture.hu-HU.min.js");
                    public static readonly string kendo_culture_hu_min_js = Url("kendo.culture.hu.min.js");
                    public static readonly string kendo_culture_hy_AM_min_js = Url("kendo.culture.hy-AM.min.js");
                    public static readonly string kendo_culture_hy_min_js = Url("kendo.culture.hy.min.js");
                    public static readonly string kendo_culture_id_ID_min_js = Url("kendo.culture.id-ID.min.js");
                    public static readonly string kendo_culture_id_min_js = Url("kendo.culture.id.min.js");
                    public static readonly string kendo_culture_ig_NG_min_js = Url("kendo.culture.ig-NG.min.js");
                    public static readonly string kendo_culture_ig_min_js = Url("kendo.culture.ig.min.js");
                    public static readonly string kendo_culture_ii_CN_min_js = Url("kendo.culture.ii-CN.min.js");
                    public static readonly string kendo_culture_ii_min_js = Url("kendo.culture.ii.min.js");
                    public static readonly string kendo_culture_is_IS_min_js = Url("kendo.culture.is-IS.min.js");
                    public static readonly string kendo_culture_is_min_js = Url("kendo.culture.is.min.js");
                    public static readonly string kendo_culture_it_CH_min_js = Url("kendo.culture.it-CH.min.js");
                    public static readonly string kendo_culture_it_IT_min_js = Url("kendo.culture.it-IT.min.js");
                    public static readonly string kendo_culture_it_min_js = Url("kendo.culture.it.min.js");
                    public static readonly string kendo_culture_iu_Cans_CA_min_js = Url("kendo.culture.iu-Cans-CA.min.js");
                    public static readonly string kendo_culture_iu_Cans_min_js = Url("kendo.culture.iu-Cans.min.js");
                    public static readonly string kendo_culture_iu_Latn_CA_min_js = Url("kendo.culture.iu-Latn-CA.min.js");
                    public static readonly string kendo_culture_iu_Latn_min_js = Url("kendo.culture.iu-Latn.min.js");
                    public static readonly string kendo_culture_iu_min_js = Url("kendo.culture.iu.min.js");
                    public static readonly string kendo_culture_ja_JP_min_js = Url("kendo.culture.ja-JP.min.js");
                    public static readonly string kendo_culture_ja_min_js = Url("kendo.culture.ja.min.js");
                    public static readonly string kendo_culture_ka_GE_min_js = Url("kendo.culture.ka-GE.min.js");
                    public static readonly string kendo_culture_ka_min_js = Url("kendo.culture.ka.min.js");
                    public static readonly string kendo_culture_kk_KZ_min_js = Url("kendo.culture.kk-KZ.min.js");
                    public static readonly string kendo_culture_kk_min_js = Url("kendo.culture.kk.min.js");
                    public static readonly string kendo_culture_kl_GL_min_js = Url("kendo.culture.kl-GL.min.js");
                    public static readonly string kendo_culture_kl_min_js = Url("kendo.culture.kl.min.js");
                    public static readonly string kendo_culture_km_KH_min_js = Url("kendo.culture.km-KH.min.js");
                    public static readonly string kendo_culture_km_min_js = Url("kendo.culture.km.min.js");
                    public static readonly string kendo_culture_kn_IN_min_js = Url("kendo.culture.kn-IN.min.js");
                    public static readonly string kendo_culture_kn_min_js = Url("kendo.culture.kn.min.js");
                    public static readonly string kendo_culture_ko_KR_min_js = Url("kendo.culture.ko-KR.min.js");
                    public static readonly string kendo_culture_ko_min_js = Url("kendo.culture.ko.min.js");
                    public static readonly string kendo_culture_kok_IN_min_js = Url("kendo.culture.kok-IN.min.js");
                    public static readonly string kendo_culture_kok_min_js = Url("kendo.culture.kok.min.js");
                    public static readonly string kendo_culture_ky_KG_min_js = Url("kendo.culture.ky-KG.min.js");
                    public static readonly string kendo_culture_ky_min_js = Url("kendo.culture.ky.min.js");
                    public static readonly string kendo_culture_lb_LU_min_js = Url("kendo.culture.lb-LU.min.js");
                    public static readonly string kendo_culture_lb_min_js = Url("kendo.culture.lb.min.js");
                    public static readonly string kendo_culture_lo_LA_min_js = Url("kendo.culture.lo-LA.min.js");
                    public static readonly string kendo_culture_lo_min_js = Url("kendo.culture.lo.min.js");
                    public static readonly string kendo_culture_lt_LT_min_js = Url("kendo.culture.lt-LT.min.js");
                    public static readonly string kendo_culture_lt_min_js = Url("kendo.culture.lt.min.js");
                    public static readonly string kendo_culture_lv_LV_min_js = Url("kendo.culture.lv-LV.min.js");
                    public static readonly string kendo_culture_lv_min_js = Url("kendo.culture.lv.min.js");
                    public static readonly string kendo_culture_mi_NZ_min_js = Url("kendo.culture.mi-NZ.min.js");
                    public static readonly string kendo_culture_mi_min_js = Url("kendo.culture.mi.min.js");
                    public static readonly string kendo_culture_mk_MK_min_js = Url("kendo.culture.mk-MK.min.js");
                    public static readonly string kendo_culture_mk_min_js = Url("kendo.culture.mk.min.js");
                    public static readonly string kendo_culture_ml_IN_min_js = Url("kendo.culture.ml-IN.min.js");
                    public static readonly string kendo_culture_ml_min_js = Url("kendo.culture.ml.min.js");
                    public static readonly string kendo_culture_mn_Cyrl_min_js = Url("kendo.culture.mn-Cyrl.min.js");
                    public static readonly string kendo_culture_mn_MN_min_js = Url("kendo.culture.mn-MN.min.js");
                    public static readonly string kendo_culture_mn_Mong_CN_min_js = Url("kendo.culture.mn-Mong-CN.min.js");
                    public static readonly string kendo_culture_mn_Mong_min_js = Url("kendo.culture.mn-Mong.min.js");
                    public static readonly string kendo_culture_mn_min_js = Url("kendo.culture.mn.min.js");
                    public static readonly string kendo_culture_moh_CA_min_js = Url("kendo.culture.moh-CA.min.js");
                    public static readonly string kendo_culture_moh_min_js = Url("kendo.culture.moh.min.js");
                    public static readonly string kendo_culture_mr_IN_min_js = Url("kendo.culture.mr-IN.min.js");
                    public static readonly string kendo_culture_mr_min_js = Url("kendo.culture.mr.min.js");
                    public static readonly string kendo_culture_ms_BN_min_js = Url("kendo.culture.ms-BN.min.js");
                    public static readonly string kendo_culture_ms_MY_min_js = Url("kendo.culture.ms-MY.min.js");
                    public static readonly string kendo_culture_ms_min_js = Url("kendo.culture.ms.min.js");
                    public static readonly string kendo_culture_mt_MT_min_js = Url("kendo.culture.mt-MT.min.js");
                    public static readonly string kendo_culture_mt_min_js = Url("kendo.culture.mt.min.js");
                    public static readonly string kendo_culture_nb_NO_min_js = Url("kendo.culture.nb-NO.min.js");
                    public static readonly string kendo_culture_nb_min_js = Url("kendo.culture.nb.min.js");
                    public static readonly string kendo_culture_ne_NP_min_js = Url("kendo.culture.ne-NP.min.js");
                    public static readonly string kendo_culture_ne_min_js = Url("kendo.culture.ne.min.js");
                    public static readonly string kendo_culture_nl_BE_min_js = Url("kendo.culture.nl-BE.min.js");
                    public static readonly string kendo_culture_nl_NL_min_js = Url("kendo.culture.nl-NL.min.js");
                    public static readonly string kendo_culture_nl_min_js = Url("kendo.culture.nl.min.js");
                    public static readonly string kendo_culture_nn_NO_min_js = Url("kendo.culture.nn-NO.min.js");
                    public static readonly string kendo_culture_nn_min_js = Url("kendo.culture.nn.min.js");
                    public static readonly string kendo_culture_no_min_js = Url("kendo.culture.no.min.js");
                    public static readonly string kendo_culture_nso_ZA_min_js = Url("kendo.culture.nso-ZA.min.js");
                    public static readonly string kendo_culture_nso_min_js = Url("kendo.culture.nso.min.js");
                    public static readonly string kendo_culture_oc_FR_min_js = Url("kendo.culture.oc-FR.min.js");
                    public static readonly string kendo_culture_oc_min_js = Url("kendo.culture.oc.min.js");
                    public static readonly string kendo_culture_or_IN_min_js = Url("kendo.culture.or-IN.min.js");
                    public static readonly string kendo_culture_or_min_js = Url("kendo.culture.or.min.js");
                    public static readonly string kendo_culture_pa_IN_min_js = Url("kendo.culture.pa-IN.min.js");
                    public static readonly string kendo_culture_pa_min_js = Url("kendo.culture.pa.min.js");
                    public static readonly string kendo_culture_pl_PL_min_js = Url("kendo.culture.pl-PL.min.js");
                    public static readonly string kendo_culture_pl_min_js = Url("kendo.culture.pl.min.js");
                    public static readonly string kendo_culture_prs_AF_min_js = Url("kendo.culture.prs-AF.min.js");
                    public static readonly string kendo_culture_prs_min_js = Url("kendo.culture.prs.min.js");
                    public static readonly string kendo_culture_ps_AF_min_js = Url("kendo.culture.ps-AF.min.js");
                    public static readonly string kendo_culture_ps_min_js = Url("kendo.culture.ps.min.js");
                    public static readonly string kendo_culture_pt_BR_min_js = Url("kendo.culture.pt-BR.min.js");
                    public static readonly string kendo_culture_pt_PT_min_js = Url("kendo.culture.pt-PT.min.js");
                    public static readonly string kendo_culture_pt_min_js = Url("kendo.culture.pt.min.js");
                    public static readonly string kendo_culture_qut_GT_min_js = Url("kendo.culture.qut-GT.min.js");
                    public static readonly string kendo_culture_qut_min_js = Url("kendo.culture.qut.min.js");
                    public static readonly string kendo_culture_quz_BO_min_js = Url("kendo.culture.quz-BO.min.js");
                    public static readonly string kendo_culture_quz_EC_min_js = Url("kendo.culture.quz-EC.min.js");
                    public static readonly string kendo_culture_quz_PE_min_js = Url("kendo.culture.quz-PE.min.js");
                    public static readonly string kendo_culture_quz_min_js = Url("kendo.culture.quz.min.js");
                    public static readonly string kendo_culture_rm_CH_min_js = Url("kendo.culture.rm-CH.min.js");
                    public static readonly string kendo_culture_rm_min_js = Url("kendo.culture.rm.min.js");
                    public static readonly string kendo_culture_ro_RO_min_js = Url("kendo.culture.ro-RO.min.js");
                    public static readonly string kendo_culture_ro_min_js = Url("kendo.culture.ro.min.js");
                    public static readonly string kendo_culture_ru_RU_min_js = Url("kendo.culture.ru-RU.min.js");
                    public static readonly string kendo_culture_ru_UA_min_js = Url("kendo.culture.ru-UA.min.js");
                    public static readonly string kendo_culture_ru_min_js = Url("kendo.culture.ru.min.js");
                    public static readonly string kendo_culture_rw_RW_min_js = Url("kendo.culture.rw-RW.min.js");
                    public static readonly string kendo_culture_rw_min_js = Url("kendo.culture.rw.min.js");
                    public static readonly string kendo_culture_sa_IN_min_js = Url("kendo.culture.sa-IN.min.js");
                    public static readonly string kendo_culture_sa_min_js = Url("kendo.culture.sa.min.js");
                    public static readonly string kendo_culture_sah_RU_min_js = Url("kendo.culture.sah-RU.min.js");
                    public static readonly string kendo_culture_sah_min_js = Url("kendo.culture.sah.min.js");
                    public static readonly string kendo_culture_se_FI_min_js = Url("kendo.culture.se-FI.min.js");
                    public static readonly string kendo_culture_se_NO_min_js = Url("kendo.culture.se-NO.min.js");
                    public static readonly string kendo_culture_se_SE_min_js = Url("kendo.culture.se-SE.min.js");
                    public static readonly string kendo_culture_se_min_js = Url("kendo.culture.se.min.js");
                    public static readonly string kendo_culture_si_LK_min_js = Url("kendo.culture.si-LK.min.js");
                    public static readonly string kendo_culture_si_min_js = Url("kendo.culture.si.min.js");
                    public static readonly string kendo_culture_sk_SK_min_js = Url("kendo.culture.sk-SK.min.js");
                    public static readonly string kendo_culture_sk_min_js = Url("kendo.culture.sk.min.js");
                    public static readonly string kendo_culture_sl_SI_min_js = Url("kendo.culture.sl-SI.min.js");
                    public static readonly string kendo_culture_sl_min_js = Url("kendo.culture.sl.min.js");
                    public static readonly string kendo_culture_sma_NO_min_js = Url("kendo.culture.sma-NO.min.js");
                    public static readonly string kendo_culture_sma_SE_min_js = Url("kendo.culture.sma-SE.min.js");
                    public static readonly string kendo_culture_sma_min_js = Url("kendo.culture.sma.min.js");
                    public static readonly string kendo_culture_smj_NO_min_js = Url("kendo.culture.smj-NO.min.js");
                    public static readonly string kendo_culture_smj_SE_min_js = Url("kendo.culture.smj-SE.min.js");
                    public static readonly string kendo_culture_smj_min_js = Url("kendo.culture.smj.min.js");
                    public static readonly string kendo_culture_smn_FI_min_js = Url("kendo.culture.smn-FI.min.js");
                    public static readonly string kendo_culture_smn_min_js = Url("kendo.culture.smn.min.js");
                    public static readonly string kendo_culture_sms_FI_min_js = Url("kendo.culture.sms-FI.min.js");
                    public static readonly string kendo_culture_sms_min_js = Url("kendo.culture.sms.min.js");
                    public static readonly string kendo_culture_sq_AL_min_js = Url("kendo.culture.sq-AL.min.js");
                    public static readonly string kendo_culture_sq_min_js = Url("kendo.culture.sq.min.js");
                    public static readonly string kendo_culture_sr_Cyrl_BA_min_js = Url("kendo.culture.sr-Cyrl-BA.min.js");
                    public static readonly string kendo_culture_sr_Cyrl_CS_min_js = Url("kendo.culture.sr-Cyrl-CS.min.js");
                    public static readonly string kendo_culture_sr_Cyrl_ME_min_js = Url("kendo.culture.sr-Cyrl-ME.min.js");
                    public static readonly string kendo_culture_sr_Cyrl_RS_min_js = Url("kendo.culture.sr-Cyrl-RS.min.js");
                    public static readonly string kendo_culture_sr_Cyrl_min_js = Url("kendo.culture.sr-Cyrl.min.js");
                    public static readonly string kendo_culture_sr_Latn_BA_min_js = Url("kendo.culture.sr-Latn-BA.min.js");
                    public static readonly string kendo_culture_sr_Latn_CS_min_js = Url("kendo.culture.sr-Latn-CS.min.js");
                    public static readonly string kendo_culture_sr_Latn_ME_min_js = Url("kendo.culture.sr-Latn-ME.min.js");
                    public static readonly string kendo_culture_sr_Latn_RS_min_js = Url("kendo.culture.sr-Latn-RS.min.js");
                    public static readonly string kendo_culture_sr_Latn_min_js = Url("kendo.culture.sr-Latn.min.js");
                    public static readonly string kendo_culture_sr_min_js = Url("kendo.culture.sr.min.js");
                    public static readonly string kendo_culture_sv_FI_min_js = Url("kendo.culture.sv-FI.min.js");
                    public static readonly string kendo_culture_sv_SE_min_js = Url("kendo.culture.sv-SE.min.js");
                    public static readonly string kendo_culture_sv_min_js = Url("kendo.culture.sv.min.js");
                    public static readonly string kendo_culture_sw_KE_min_js = Url("kendo.culture.sw-KE.min.js");
                    public static readonly string kendo_culture_sw_min_js = Url("kendo.culture.sw.min.js");
                    public static readonly string kendo_culture_syr_SY_min_js = Url("kendo.culture.syr-SY.min.js");
                    public static readonly string kendo_culture_syr_min_js = Url("kendo.culture.syr.min.js");
                    public static readonly string kendo_culture_ta_IN_min_js = Url("kendo.culture.ta-IN.min.js");
                    public static readonly string kendo_culture_ta_min_js = Url("kendo.culture.ta.min.js");
                    public static readonly string kendo_culture_te_IN_min_js = Url("kendo.culture.te-IN.min.js");
                    public static readonly string kendo_culture_te_min_js = Url("kendo.culture.te.min.js");
                    public static readonly string kendo_culture_tg_Cyrl_TJ_min_js = Url("kendo.culture.tg-Cyrl-TJ.min.js");
                    public static readonly string kendo_culture_tg_Cyrl_min_js = Url("kendo.culture.tg-Cyrl.min.js");
                    public static readonly string kendo_culture_tg_min_js = Url("kendo.culture.tg.min.js");
                    public static readonly string kendo_culture_th_TH_min_js = Url("kendo.culture.th-TH.min.js");
                    public static readonly string kendo_culture_th_min_js = Url("kendo.culture.th.min.js");
                    public static readonly string kendo_culture_tk_TM_min_js = Url("kendo.culture.tk-TM.min.js");
                    public static readonly string kendo_culture_tk_min_js = Url("kendo.culture.tk.min.js");
                    public static readonly string kendo_culture_tn_ZA_min_js = Url("kendo.culture.tn-ZA.min.js");
                    public static readonly string kendo_culture_tn_min_js = Url("kendo.culture.tn.min.js");
                    public static readonly string kendo_culture_tr_TR_min_js = Url("kendo.culture.tr-TR.min.js");
                    public static readonly string kendo_culture_tr_min_js = Url("kendo.culture.tr.min.js");
                    public static readonly string kendo_culture_tt_RU_min_js = Url("kendo.culture.tt-RU.min.js");
                    public static readonly string kendo_culture_tt_min_js = Url("kendo.culture.tt.min.js");
                    public static readonly string kendo_culture_tzm_Latn_DZ_min_js = Url("kendo.culture.tzm-Latn-DZ.min.js");
                    public static readonly string kendo_culture_tzm_Latn_min_js = Url("kendo.culture.tzm-Latn.min.js");
                    public static readonly string kendo_culture_tzm_min_js = Url("kendo.culture.tzm.min.js");
                    public static readonly string kendo_culture_ug_CN_min_js = Url("kendo.culture.ug-CN.min.js");
                    public static readonly string kendo_culture_ug_min_js = Url("kendo.culture.ug.min.js");
                    public static readonly string kendo_culture_uk_UA_min_js = Url("kendo.culture.uk-UA.min.js");
                    public static readonly string kendo_culture_uk_min_js = Url("kendo.culture.uk.min.js");
                    public static readonly string kendo_culture_ur_PK_min_js = Url("kendo.culture.ur-PK.min.js");
                    public static readonly string kendo_culture_ur_min_js = Url("kendo.culture.ur.min.js");
                    public static readonly string kendo_culture_uz_Cyrl_UZ_min_js = Url("kendo.culture.uz-Cyrl-UZ.min.js");
                    public static readonly string kendo_culture_uz_Cyrl_min_js = Url("kendo.culture.uz-Cyrl.min.js");
                    public static readonly string kendo_culture_uz_Latn_UZ_min_js = Url("kendo.culture.uz-Latn-UZ.min.js");
                    public static readonly string kendo_culture_uz_Latn_min_js = Url("kendo.culture.uz-Latn.min.js");
                    public static readonly string kendo_culture_uz_min_js = Url("kendo.culture.uz.min.js");
                    public static readonly string kendo_culture_vi_VN_min_js = Url("kendo.culture.vi-VN.min.js");
                    public static readonly string kendo_culture_vi_min_js = Url("kendo.culture.vi.min.js");
                    public static readonly string kendo_culture_wo_SN_min_js = Url("kendo.culture.wo-SN.min.js");
                    public static readonly string kendo_culture_wo_min_js = Url("kendo.culture.wo.min.js");
                    public static readonly string kendo_culture_xh_ZA_min_js = Url("kendo.culture.xh-ZA.min.js");
                    public static readonly string kendo_culture_xh_min_js = Url("kendo.culture.xh.min.js");
                    public static readonly string kendo_culture_yo_NG_min_js = Url("kendo.culture.yo-NG.min.js");
                    public static readonly string kendo_culture_yo_min_js = Url("kendo.culture.yo.min.js");
                    public static readonly string kendo_culture_zh_CHS_min_js = Url("kendo.culture.zh-CHS.min.js");
                    public static readonly string kendo_culture_zh_CHT_min_js = Url("kendo.culture.zh-CHT.min.js");
                    public static readonly string kendo_culture_zh_CN_min_js = Url("kendo.culture.zh-CN.min.js");
                    public static readonly string kendo_culture_zh_Hans_min_js = Url("kendo.culture.zh-Hans.min.js");
                    public static readonly string kendo_culture_zh_Hant_min_js = Url("kendo.culture.zh-Hant.min.js");
                    public static readonly string kendo_culture_zh_HK_min_js = Url("kendo.culture.zh-HK.min.js");
                    public static readonly string kendo_culture_zh_MO_min_js = Url("kendo.culture.zh-MO.min.js");
                    public static readonly string kendo_culture_zh_SG_min_js = Url("kendo.culture.zh-SG.min.js");
                    public static readonly string kendo_culture_zh_TW_min_js = Url("kendo.culture.zh-TW.min.js");
                    public static readonly string kendo_culture_zh_min_js = Url("kendo.culture.zh.min.js");
                    public static readonly string kendo_culture_zu_ZA_min_js = Url("kendo.culture.zu-ZA.min.js");
                    public static readonly string kendo_culture_zu_min_js = Url("kendo.culture.zu.min.js");
                }
            
                public static readonly string jquery_min_js = Url("jquery.min.js");
                public static readonly string jquery_min_map = Url("jquery.min.map");
                public static readonly string kendo_autocomplete_min_js = Url("kendo.autocomplete.min.js");
                public static readonly string kendo_autocomplete_min_js_map = Url("kendo.autocomplete.min.js.map");
                public static readonly string kendo_binder_min_js = Url("kendo.binder.min.js");
                public static readonly string kendo_binder_min_js_map = Url("kendo.binder.min.js.map");
                public static readonly string kendo_button_min_js = Url("kendo.button.min.js");
                public static readonly string kendo_button_min_js_map = Url("kendo.button.min.js.map");
                public static readonly string kendo_calendar_min_js = Url("kendo.calendar.min.js");
                public static readonly string kendo_calendar_min_js_map = Url("kendo.calendar.min.js.map");
                public static readonly string kendo_colorpicker_min_js = Url("kendo.colorpicker.min.js");
                public static readonly string kendo_colorpicker_min_js_map = Url("kendo.colorpicker.min.js.map");
                public static readonly string kendo_columnmenu_min_js = Url("kendo.columnmenu.min.js");
                public static readonly string kendo_columnmenu_min_js_map = Url("kendo.columnmenu.min.js.map");
                public static readonly string kendo_combobox_min_js = Url("kendo.combobox.min.js");
                public static readonly string kendo_combobox_min_js_map = Url("kendo.combobox.min.js.map");
                public static readonly string kendo_core_min_js = Url("kendo.core.min.js");
                public static readonly string kendo_core_min_js_map = Url("kendo.core.min.js.map");
                public static readonly string kendo_data_min_js = Url("kendo.data.min.js");
                public static readonly string kendo_data_min_js_map = Url("kendo.data.min.js.map");
                public static readonly string kendo_data_odata_min_js = Url("kendo.data.odata.min.js");
                public static readonly string kendo_data_odata_min_js_map = Url("kendo.data.odata.min.js.map");
                public static readonly string kendo_data_signalr_min_js = Url("kendo.data.signalr.min.js");
                public static readonly string kendo_data_signalr_min_js_map = Url("kendo.data.signalr.min.js.map");
                public static readonly string kendo_data_xml_min_js = Url("kendo.data.xml.min.js");
                public static readonly string kendo_data_xml_min_js_map = Url("kendo.data.xml.min.js.map");
                public static readonly string kendo_datepicker_min_js = Url("kendo.datepicker.min.js");
                public static readonly string kendo_datepicker_min_js_map = Url("kendo.datepicker.min.js.map");
                public static readonly string kendo_datetimepicker_min_js = Url("kendo.datetimepicker.min.js");
                public static readonly string kendo_datetimepicker_min_js_map = Url("kendo.datetimepicker.min.js.map");
                public static readonly string kendo_draganddrop_min_js = Url("kendo.draganddrop.min.js");
                public static readonly string kendo_draganddrop_min_js_map = Url("kendo.draganddrop.min.js.map");
                public static readonly string kendo_dropdownlist_min_js = Url("kendo.dropdownlist.min.js");
                public static readonly string kendo_dropdownlist_min_js_map = Url("kendo.dropdownlist.min.js.map");
                public static readonly string kendo_editable_min_js = Url("kendo.editable.min.js");
                public static readonly string kendo_editable_min_js_map = Url("kendo.editable.min.js.map");
                public static readonly string kendo_editor_min_js = Url("kendo.editor.min.js");
                public static readonly string kendo_editor_min_js_map = Url("kendo.editor.min.js.map");
                public static readonly string kendo_filtermenu_min_js = Url("kendo.filtermenu.min.js");
                public static readonly string kendo_filtermenu_min_js_map = Url("kendo.filtermenu.min.js.map");
                public static readonly string kendo_fx_min_js = Url("kendo.fx.min.js");
                public static readonly string kendo_fx_min_js_map = Url("kendo.fx.min.js.map");
                public static readonly string kendo_grid_min_js = Url("kendo.grid.min.js");
                public static readonly string kendo_grid_min_js_map = Url("kendo.grid.min.js.map");
                public static readonly string kendo_groupable_min_js = Url("kendo.groupable.min.js");
                public static readonly string kendo_groupable_min_js_map = Url("kendo.groupable.min.js.map");
                public static readonly string kendo_imagebrowser_min_js = Url("kendo.imagebrowser.min.js");
                public static readonly string kendo_imagebrowser_min_js_map = Url("kendo.imagebrowser.min.js.map");
                public static readonly string kendo_list_min_js = Url("kendo.list.min.js");
                public static readonly string kendo_list_min_js_map = Url("kendo.list.min.js.map");
                public static readonly string kendo_listview_min_js = Url("kendo.listview.min.js");
                public static readonly string kendo_listview_min_js_map = Url("kendo.listview.min.js.map");
                public static readonly string kendo_maskedtextbox_min_js = Url("kendo.maskedtextbox.min.js");
                public static readonly string kendo_maskedtextbox_min_js_map = Url("kendo.maskedtextbox.min.js.map");
                public static readonly string kendo_menu_min_js = Url("kendo.menu.min.js");
                public static readonly string kendo_menu_min_js_map = Url("kendo.menu.min.js.map");
                public static readonly string kendo_mobile_actionsheet_min_js = Url("kendo.mobile.actionsheet.min.js");
                public static readonly string kendo_mobile_actionsheet_min_js_map = Url("kendo.mobile.actionsheet.min.js.map");
                public static readonly string kendo_mobile_application_min_js = Url("kendo.mobile.application.min.js");
                public static readonly string kendo_mobile_application_min_js_map = Url("kendo.mobile.application.min.js.map");
                public static readonly string kendo_mobile_loader_min_js = Url("kendo.mobile.loader.min.js");
                public static readonly string kendo_mobile_loader_min_js_map = Url("kendo.mobile.loader.min.js.map");
                public static readonly string kendo_mobile_pane_min_js = Url("kendo.mobile.pane.min.js");
                public static readonly string kendo_mobile_pane_min_js_map = Url("kendo.mobile.pane.min.js.map");
                public static readonly string kendo_mobile_popover_min_js = Url("kendo.mobile.popover.min.js");
                public static readonly string kendo_mobile_popover_min_js_map = Url("kendo.mobile.popover.min.js.map");
                public static readonly string kendo_mobile_scroller_min_js = Url("kendo.mobile.scroller.min.js");
                public static readonly string kendo_mobile_scroller_min_js_map = Url("kendo.mobile.scroller.min.js.map");
                public static readonly string kendo_mobile_shim_min_js = Url("kendo.mobile.shim.min.js");
                public static readonly string kendo_mobile_shim_min_js_map = Url("kendo.mobile.shim.min.js.map");
                public static readonly string kendo_mobile_view_min_js = Url("kendo.mobile.view.min.js");
                public static readonly string kendo_mobile_view_min_js_map = Url("kendo.mobile.view.min.js.map");
                public static readonly string kendo_multiselect_min_js = Url("kendo.multiselect.min.js");
                public static readonly string kendo_multiselect_min_js_map = Url("kendo.multiselect.min.js.map");
                public static readonly string kendo_notification_min_js = Url("kendo.notification.min.js");
                public static readonly string kendo_notification_min_js_map = Url("kendo.notification.min.js.map");
                public static readonly string kendo_numerictextbox_min_js = Url("kendo.numerictextbox.min.js");
                public static readonly string kendo_numerictextbox_min_js_map = Url("kendo.numerictextbox.min.js.map");
                public static readonly string kendo_pager_min_js = Url("kendo.pager.min.js");
                public static readonly string kendo_pager_min_js_map = Url("kendo.pager.min.js.map");
                public static readonly string kendo_panelbar_min_js = Url("kendo.panelbar.min.js");
                public static readonly string kendo_panelbar_min_js_map = Url("kendo.panelbar.min.js.map");
                public static readonly string kendo_popup_min_js = Url("kendo.popup.min.js");
                public static readonly string kendo_popup_min_js_map = Url("kendo.popup.min.js.map");
                public static readonly string kendo_progressbar_min_js = Url("kendo.progressbar.min.js");
                public static readonly string kendo_progressbar_min_js_map = Url("kendo.progressbar.min.js.map");
                public static readonly string kendo_reorderable_min_js = Url("kendo.reorderable.min.js");
                public static readonly string kendo_reorderable_min_js_map = Url("kendo.reorderable.min.js.map");
                public static readonly string kendo_resizable_min_js = Url("kendo.resizable.min.js");
                public static readonly string kendo_resizable_min_js_map = Url("kendo.resizable.min.js.map");
                public static readonly string kendo_router_min_js = Url("kendo.router.min.js");
                public static readonly string kendo_router_min_js_map = Url("kendo.router.min.js.map");
                public static readonly string kendo_scheduler_agendaview_min_js = Url("kendo.scheduler.agendaview.min.js");
                public static readonly string kendo_scheduler_agendaview_min_js_map = Url("kendo.scheduler.agendaview.min.js.map");
                public static readonly string kendo_scheduler_dayview_min_js = Url("kendo.scheduler.dayview.min.js");
                public static readonly string kendo_scheduler_dayview_min_js_map = Url("kendo.scheduler.dayview.min.js.map");
                public static readonly string kendo_scheduler_min_js = Url("kendo.scheduler.min.js");
                public static readonly string kendo_scheduler_min_js_map = Url("kendo.scheduler.min.js.map");
                public static readonly string kendo_scheduler_monthview_min_js = Url("kendo.scheduler.monthview.min.js");
                public static readonly string kendo_scheduler_monthview_min_js_map = Url("kendo.scheduler.monthview.min.js.map");
                public static readonly string kendo_scheduler_recurrence_min_js = Url("kendo.scheduler.recurrence.min.js");
                public static readonly string kendo_scheduler_recurrence_min_js_map = Url("kendo.scheduler.recurrence.min.js.map");
                public static readonly string kendo_scheduler_view_min_js = Url("kendo.scheduler.view.min.js");
                public static readonly string kendo_scheduler_view_min_js_map = Url("kendo.scheduler.view.min.js.map");
                public static readonly string kendo_selectable_min_js = Url("kendo.selectable.min.js");
                public static readonly string kendo_selectable_min_js_map = Url("kendo.selectable.min.js.map");
                public static readonly string kendo_slider_min_js = Url("kendo.slider.min.js");
                public static readonly string kendo_slider_min_js_map = Url("kendo.slider.min.js.map");
                public static readonly string kendo_sortable_min_js = Url("kendo.sortable.min.js");
                public static readonly string kendo_sortable_min_js_map = Url("kendo.sortable.min.js.map");
                public static readonly string kendo_splitter_min_js = Url("kendo.splitter.min.js");
                public static readonly string kendo_splitter_min_js_map = Url("kendo.splitter.min.js.map");
                public static readonly string kendo_tabstrip_min_js = Url("kendo.tabstrip.min.js");
                public static readonly string kendo_tabstrip_min_js_map = Url("kendo.tabstrip.min.js.map");
                public static readonly string kendo_timepicker_min_js = Url("kendo.timepicker.min.js");
                public static readonly string kendo_timepicker_min_js_map = Url("kendo.timepicker.min.js.map");
                public static readonly string kendo_timezones_min_js = Url("kendo.timezones.min.js");
                public static readonly string kendo_tooltip_min_js = Url("kendo.tooltip.min.js");
                public static readonly string kendo_tooltip_min_js_map = Url("kendo.tooltip.min.js.map");
                public static readonly string kendo_treeview_min_js = Url("kendo.treeview.min.js");
                public static readonly string kendo_treeview_min_js_map = Url("kendo.treeview.min.js.map");
                public static readonly string kendo_upload_min_js = Url("kendo.upload.min.js");
                public static readonly string kendo_upload_min_js_map = Url("kendo.upload.min.js.map");
                public static readonly string kendo_userevents_min_js = Url("kendo.userevents.min.js");
                public static readonly string kendo_userevents_min_js_map = Url("kendo.userevents.min.js.map");
                public static readonly string kendo_validator_min_js = Url("kendo.validator.min.js");
                public static readonly string kendo_validator_min_js_map = Url("kendo.validator.min.js.map");
                public static readonly string kendo_view_min_js = Url("kendo.view.min.js");
                public static readonly string kendo_view_min_js_map = Url("kendo.view.min.js.map");
                public static readonly string kendo_web_min_js = Url("kendo.web.min.js");
                public static readonly string kendo_web_min_js_map = Url("kendo.web.min.js.map");
                public static readonly string kendo_window_min_js = Url("kendo.window.min.js");
                public static readonly string kendo_window_min_js_map = Url("kendo.window.min.js.map");
            }
        
        }
    
        public static readonly string modernizr_2_8_3_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/modernizr-2.8.3.min.js") ? Url("modernizr-2.8.3.min.js") : Url("modernizr-2.8.3.js");
        public static readonly string npm_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/npm.min.js") ? Url("npm.min.js") : Url("npm.js");
        public static readonly string respond_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/respond.min.js") ? Url("respond.min.js") : Url("respond.js");
        public static readonly string respond_matchmedia_addListener_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/respond.matchmedia.addListener.min.js") ? Url("respond.matchmedia.addListener.min.js") : Url("respond.matchmedia.addListener.js");
        public static readonly string respond_matchmedia_addListener_min_js = Url("respond.matchmedia.addListener.min.js");
        public static readonly string respond_min_js = Url("respond.min.js");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Site {
            private const string URLPATH = "~/Scripts/Site";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string GeneralScripts_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/GeneralScripts.min.js") ? Url("GeneralScripts.min.js") : Url("GeneralScripts.js");
        }
    
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Content {
        private const string URLPATH = "~/Content";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        public static readonly string bootstrap_theme_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap-theme.min.css") ? Url("bootstrap-theme.min.css") : Url("bootstrap-theme.css");
             
        public static readonly string bootstrap_theme_css_map = Url("bootstrap-theme.css.map");
        public static readonly string bootstrap_theme_min_css = Url("bootstrap-theme.min.css");
        public static readonly string bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap.min.css") ? Url("bootstrap.min.css") : Url("bootstrap.css");
             
        public static readonly string bootstrap_css_map = Url("bootstrap.css.map");
        public static readonly string bootstrap_min_css = Url("bootstrap.min.css");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Images {
            private const string URLPATH = "~/Content/Images";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string glyphicons_halflings_regular_eot = Url("glyphicons-halflings-regular.eot");
            public static readonly string glyphicons_halflings_regular_svg = Url("glyphicons-halflings-regular.svg");
            public static readonly string glyphicons_halflings_regular_ttf = Url("glyphicons-halflings-regular.ttf");
            public static readonly string glyphicons_halflings_regular_woff = Url("glyphicons-halflings-regular.woff");
            public static readonly string logo_png = Url("logo.png");
            public static readonly string logoPublicarBN_png = Url("logoPublicarBN.png");
            public static readonly string OpenSans_Regular_eot = Url("OpenSans-Regular.eot");
            public static readonly string OpenSans_Regular_otf = Url("OpenSans-Regular.otf");
            public static readonly string OpenSans_Regular_ttf = Url("OpenSans-Regular.ttf");
            public static readonly string OpenSans_Regular_woff = Url("OpenSans-Regular.woff");
            public static readonly string POBOBackground3Small_jpg = Url("POBOBackground3Small.jpg");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class kendo {
            private const string URLPATH = "~/Content/kendo";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class _2014_1_318 {
                private const string URLPATH = "~/Content/kendo/2014.1.318";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class Black {
                    private const string URLPATH = "~/Content/kendo/2014.1.318/Black";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string editor_png = Url("editor.png");
                    public static readonly string imagebrowser_png = Url("imagebrowser.png");
                    public static readonly string indeterminate_gif = Url("indeterminate.gif");
                    public static readonly string loading_image_gif = Url("loading-image.gif");
                    public static readonly string loading_gif = Url("loading.gif");
                    public static readonly string loading_2x_gif = Url("loading_2x.gif");
                    public static readonly string slider_h_gif = Url("slider-h.gif");
                    public static readonly string slider_v_gif = Url("slider-v.gif");
                    public static readonly string sprite_png = Url("sprite.png");
                    public static readonly string sprite_2x_png = Url("sprite_2x.png");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class BlueOpal {
                    private const string URLPATH = "~/Content/kendo/2014.1.318/BlueOpal";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string editor_png = Url("editor.png");
                    public static readonly string imagebrowser_png = Url("imagebrowser.png");
                    public static readonly string indeterminate_gif = Url("indeterminate.gif");
                    public static readonly string loading_image_gif = Url("loading-image.gif");
                    public static readonly string loading_gif = Url("loading.gif");
                    public static readonly string loading_2x_gif = Url("loading_2x.gif");
                    public static readonly string slider_h_gif = Url("slider-h.gif");
                    public static readonly string slider_v_gif = Url("slider-v.gif");
                    public static readonly string sprite_png = Url("sprite.png");
                    public static readonly string sprite_2x_png = Url("sprite_2x.png");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class Bootstrap {
                    private const string URLPATH = "~/Content/kendo/2014.1.318/Bootstrap";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string editor_png = Url("editor.png");
                    public static readonly string imagebrowser_png = Url("imagebrowser.png");
                    public static readonly string indeterminate_gif = Url("indeterminate.gif");
                    public static readonly string loading_image_gif = Url("loading-image.gif");
                    public static readonly string loading_gif = Url("loading.gif");
                    public static readonly string loading_2x_gif = Url("loading_2x.gif");
                    public static readonly string slider_h_gif = Url("slider-h.gif");
                    public static readonly string slider_v_gif = Url("slider-v.gif");
                    public static readonly string sprite_png = Url("sprite.png");
                    public static readonly string sprite_2x_png = Url("sprite_2x.png");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class Default {
                    private const string URLPATH = "~/Content/kendo/2014.1.318/Default";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string editor_png = Url("editor.png");
                    public static readonly string imagebrowser_png = Url("imagebrowser.png");
                    public static readonly string indeterminate_gif = Url("indeterminate.gif");
                    public static readonly string loading_image_gif = Url("loading-image.gif");
                    public static readonly string loading_gif = Url("loading.gif");
                    public static readonly string loading_2x_gif = Url("loading_2x.gif");
                    public static readonly string slider_h_gif = Url("slider-h.gif");
                    public static readonly string slider_v_gif = Url("slider-v.gif");
                    public static readonly string sprite_png = Url("sprite.png");
                    public static readonly string sprite_2x_png = Url("sprite_2x.png");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class Flat {
                    private const string URLPATH = "~/Content/kendo/2014.1.318/Flat";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string editor_png = Url("editor.png");
                    public static readonly string imagebrowser_png = Url("imagebrowser.png");
                    public static readonly string indeterminate_gif = Url("indeterminate.gif");
                    public static readonly string loading_image_gif = Url("loading-image.gif");
                    public static readonly string loading_gif = Url("loading.gif");
                    public static readonly string loading_2x_gif = Url("loading_2x.gif");
                    public static readonly string slider_h_gif = Url("slider-h.gif");
                    public static readonly string slider_v_gif = Url("slider-v.gif");
                    public static readonly string sprite_png = Url("sprite.png");
                    public static readonly string sprite_2x_png = Url("sprite_2x.png");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class HighContrast {
                    private const string URLPATH = "~/Content/kendo/2014.1.318/HighContrast";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string editor_png = Url("editor.png");
                    public static readonly string imagebrowser_png = Url("imagebrowser.png");
                    public static readonly string indeterminate_gif = Url("indeterminate.gif");
                    public static readonly string loading_image_gif = Url("loading-image.gif");
                    public static readonly string loading_gif = Url("loading.gif");
                    public static readonly string loading_2x_gif = Url("loading_2x.gif");
                    public static readonly string slider_h_gif = Url("slider-h.gif");
                    public static readonly string slider_v_gif = Url("slider-v.gif");
                    public static readonly string sprite_png = Url("sprite.png");
                    public static readonly string sprite_2x_png = Url("sprite_2x.png");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class images {
                    private const string URLPATH = "~/Content/kendo/2014.1.318/images";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string kendoui_ttf = Url("kendoui.ttf");
                    public static readonly string kendoui_woff = Url("kendoui.woff");
                }
            
                public static readonly string kendo_black_min_css = Url("kendo.black.min.css");
                public static readonly string kendo_black_mobile_min_css = Url("kendo.black.mobile.min.css");
                public static readonly string kendo_blueopal_min_css = Url("kendo.blueopal.min.css");
                public static readonly string kendo_blueopal_mobile_min_css = Url("kendo.blueopal.mobile.min.css");
                public static readonly string kendo_bootstrap_min_css = Url("kendo.bootstrap.min.css");
                public static readonly string kendo_bootstrap_mobile_min_css = Url("kendo.bootstrap.mobile.min.css");
                public static readonly string kendo_common_bootstrap_core_min_css = Url("kendo.common-bootstrap.core.min.css");
                public static readonly string kendo_common_bootstrap_min_css = Url("kendo.common-bootstrap.min.css");
                public static readonly string kendo_common_core_min_css = Url("kendo.common.core.min.css");
                public static readonly string kendo_common_min_css = Url("kendo.common.min.css");
                public static readonly string kendo_default_min_css = Url("kendo.default.min.css");
                public static readonly string kendo_default_mobile_min_css = Url("kendo.default.mobile.min.css");
                public static readonly string kendo_flat_min_css = Url("kendo.flat.min.css");
                public static readonly string kendo_flat_mobile_min_css = Url("kendo.flat.mobile.min.css");
                public static readonly string kendo_highcontrast_min_css = Url("kendo.highcontrast.min.css");
                public static readonly string kendo_highcontrast_mobile_min_css = Url("kendo.highcontrast.mobile.min.css");
                public static readonly string kendo_metro_min_css = Url("kendo.metro.min.css");
                public static readonly string kendo_metro_mobile_min_css = Url("kendo.metro.mobile.min.css");
                public static readonly string kendo_metroblack_min_css = Url("kendo.metroblack.min.css");
                public static readonly string kendo_metroblack_mobile_min_css = Url("kendo.metroblack.mobile.min.css");
                public static readonly string kendo_moonlight_min_css = Url("kendo.moonlight.min.css");
                public static readonly string kendo_moonlight_mobile_min_css = Url("kendo.moonlight.mobile.min.css");
                public static readonly string kendo_rtl_min_css = Url("kendo.rtl.min.css");
                public static readonly string kendo_silver_min_css = Url("kendo.silver.min.css");
                public static readonly string kendo_silver_mobile_min_css = Url("kendo.silver.mobile.min.css");
                public static readonly string kendo_uniform_min_css = Url("kendo.uniform.min.css");
                public static readonly string kendo_uniform_mobile_min_css = Url("kendo.uniform.mobile.min.css");
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class Metro {
                    private const string URLPATH = "~/Content/kendo/2014.1.318/Metro";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string editor_png = Url("editor.png");
                    public static readonly string imagebrowser_png = Url("imagebrowser.png");
                    public static readonly string indeterminate_gif = Url("indeterminate.gif");
                    public static readonly string loading_image_gif = Url("loading-image.gif");
                    public static readonly string loading_gif = Url("loading.gif");
                    public static readonly string loading_2x_gif = Url("loading_2x.gif");
                    public static readonly string slider_h_gif = Url("slider-h.gif");
                    public static readonly string slider_v_gif = Url("slider-v.gif");
                    public static readonly string sprite_png = Url("sprite.png");
                    public static readonly string sprite_2x_png = Url("sprite_2x.png");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class MetroBlack {
                    private const string URLPATH = "~/Content/kendo/2014.1.318/MetroBlack";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string editor_png = Url("editor.png");
                    public static readonly string imagebrowser_png = Url("imagebrowser.png");
                    public static readonly string indeterminate_gif = Url("indeterminate.gif");
                    public static readonly string loading_image_gif = Url("loading-image.gif");
                    public static readonly string loading_gif = Url("loading.gif");
                    public static readonly string loading_2x_gif = Url("loading_2x.gif");
                    public static readonly string slider_h_gif = Url("slider-h.gif");
                    public static readonly string slider_v_gif = Url("slider-v.gif");
                    public static readonly string sprite_png = Url("sprite.png");
                    public static readonly string sprite_2x_png = Url("sprite_2x.png");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class Moonlight {
                    private const string URLPATH = "~/Content/kendo/2014.1.318/Moonlight";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string editor_png = Url("editor.png");
                    public static readonly string imagebrowser_png = Url("imagebrowser.png");
                    public static readonly string indeterminate_gif = Url("indeterminate.gif");
                    public static readonly string loading_image_gif = Url("loading-image.gif");
                    public static readonly string loading_gif = Url("loading.gif");
                    public static readonly string loading_2x_gif = Url("loading_2x.gif");
                    public static readonly string slider_h_gif = Url("slider-h.gif");
                    public static readonly string slider_v_gif = Url("slider-v.gif");
                    public static readonly string sprite_png = Url("sprite.png");
                    public static readonly string sprite_2x_png = Url("sprite_2x.png");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class Silver {
                    private const string URLPATH = "~/Content/kendo/2014.1.318/Silver";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string editor_png = Url("editor.png");
                    public static readonly string imagebrowser_png = Url("imagebrowser.png");
                    public static readonly string indeterminate_gif = Url("indeterminate.gif");
                    public static readonly string loading_image_gif = Url("loading-image.gif");
                    public static readonly string loading_gif = Url("loading.gif");
                    public static readonly string loading_2x_gif = Url("loading_2x.gif");
                    public static readonly string slider_h_gif = Url("slider-h.gif");
                    public static readonly string slider_v_gif = Url("slider-v.gif");
                    public static readonly string sprite_png = Url("sprite.png");
                    public static readonly string sprite_2x_png = Url("sprite_2x.png");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class textures {
                    private const string URLPATH = "~/Content/kendo/2014.1.318/textures";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string brushed_metal_png = Url("brushed-metal.png");
                    public static readonly string dots1_png = Url("dots1.png");
                    public static readonly string dots10_png = Url("dots10.png");
                    public static readonly string dots11_png = Url("dots11.png");
                    public static readonly string dots12_png = Url("dots12.png");
                    public static readonly string dots13_png = Url("dots13.png");
                    public static readonly string dots2_png = Url("dots2.png");
                    public static readonly string dots3_png = Url("dots3.png");
                    public static readonly string dots4_png = Url("dots4.png");
                    public static readonly string dots5_png = Url("dots5.png");
                    public static readonly string dots6_png = Url("dots6.png");
                    public static readonly string dots7_png = Url("dots7.png");
                    public static readonly string dots8_png = Url("dots8.png");
                    public static readonly string dots9_png = Url("dots9.png");
                    public static readonly string glass_lighter_png = Url("glass-lighter.png");
                    public static readonly string glass_png = Url("glass.png");
                    public static readonly string highlight_png = Url("highlight.png");
                    public static readonly string hsv_gradient_png = Url("hsv-gradient.png");
                    public static readonly string hue_png = Url("hue.png");
                    public static readonly string leather1_png = Url("leather1.png");
                    public static readonly string leather2_png = Url("leather2.png");
                    public static readonly string noise_png = Url("noise.png");
                    public static readonly string stripe1_png = Url("stripe1.png");
                    public static readonly string stripe2_png = Url("stripe2.png");
                    public static readonly string stripe3_png = Url("stripe3.png");
                    public static readonly string stripe4_png = Url("stripe4.png");
                    public static readonly string stripe5_png = Url("stripe5.png");
                    public static readonly string stripe6_png = Url("stripe6.png");
                    public static readonly string transparency_png = Url("transparency.png");
                    public static readonly string transtexture_png = Url("transtexture.png");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class Uniform {
                    private const string URLPATH = "~/Content/kendo/2014.1.318/Uniform";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string editor_png = Url("editor.png");
                    public static readonly string imagebrowser_png = Url("imagebrowser.png");
                    public static readonly string indeterminate_gif = Url("indeterminate.gif");
                    public static readonly string loading_image_gif = Url("loading-image.gif");
                    public static readonly string loading_gif = Url("loading.gif");
                    public static readonly string loading_2x_gif = Url("loading_2x.gif");
                    public static readonly string slider_h_gif = Url("slider-h.gif");
                    public static readonly string slider_v_gif = Url("slider-v.gif");
                    public static readonly string sprite_png = Url("sprite.png");
                    public static readonly string sprite_2x_png = Url("sprite_2x.png");
                }
            
            }
        
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Styles {
            private const string URLPATH = "~/Content/Styles";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Site {
                private const string URLPATH = "~/Content/Styles/Site";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string POBOCustomer_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/POBOCustomer.min.css") ? Url("POBOCustomer.min.css") : Url("POBOCustomer.css");
                     
                public static readonly string POBOFooter_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/POBOFooter.min.css") ? Url("POBOFooter.min.css") : Url("POBOFooter.css");
                     
                public static readonly string POBOHeader_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/POBOHeader.min.css") ? Url("POBOHeader.min.css") : Url("POBOHeader.css");
                     
                public static readonly string POBOLayout_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/POBOLayout.min.css") ? Url("POBOLayout.min.css") : Url("POBOLayout.css");
                     
                public static readonly string POBOLogIn_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/POBOLogIn.min.css") ? Url("POBOLogIn.min.css") : Url("POBOLogIn.css");
                     
                public static readonly string POBOLogInProviders_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/POBOLogInProviders.min.css") ? Url("POBOLogInProviders.min.css") : Url("POBOLogInProviders.css");
                     
                public static readonly string POBOProvider_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/POBOProvider.min.css") ? Url("POBOProvider.min.css") : Url("POBOProvider.css");
                     
            }
        
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class themes {
            private const string URLPATH = "~/Content/themes";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class @base {
                private const string URLPATH = "~/Content/themes/base";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string accordion_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/accordion.min.css") ? Url("accordion.min.css") : Url("accordion.css");
                     
                public static readonly string all_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/all.min.css") ? Url("all.min.css") : Url("all.css");
                     
                public static readonly string autocomplete_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/autocomplete.min.css") ? Url("autocomplete.min.css") : Url("autocomplete.css");
                     
                public static readonly string base_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/base.min.css") ? Url("base.min.css") : Url("base.css");
                     
                public static readonly string button_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/button.min.css") ? Url("button.min.css") : Url("button.css");
                     
                public static readonly string core_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/core.min.css") ? Url("core.min.css") : Url("core.css");
                     
                public static readonly string datepicker_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/datepicker.min.css") ? Url("datepicker.min.css") : Url("datepicker.css");
                     
                public static readonly string dialog_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/dialog.min.css") ? Url("dialog.min.css") : Url("dialog.css");
                     
                public static readonly string draggable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/draggable.min.css") ? Url("draggable.min.css") : Url("draggable.css");
                     
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class images {
                    private const string URLPATH = "~/Content/themes/base/images";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string ui_bg_flat_0_aaaaaa_40x100_png = Url("ui-bg_flat_0_aaaaaa_40x100.png");
                    public static readonly string ui_bg_flat_75_ffffff_40x100_png = Url("ui-bg_flat_75_ffffff_40x100.png");
                    public static readonly string ui_bg_glass_55_fbf9ee_1x400_png = Url("ui-bg_glass_55_fbf9ee_1x400.png");
                    public static readonly string ui_bg_glass_65_ffffff_1x400_png = Url("ui-bg_glass_65_ffffff_1x400.png");
                    public static readonly string ui_bg_glass_75_dadada_1x400_png = Url("ui-bg_glass_75_dadada_1x400.png");
                    public static readonly string ui_bg_glass_75_e6e6e6_1x400_png = Url("ui-bg_glass_75_e6e6e6_1x400.png");
                    public static readonly string ui_bg_glass_95_fef1ec_1x400_png = Url("ui-bg_glass_95_fef1ec_1x400.png");
                    public static readonly string ui_bg_highlight_soft_75_cccccc_1x100_png = Url("ui-bg_highlight-soft_75_cccccc_1x100.png");
                    public static readonly string ui_icons_222222_256x240_png = Url("ui-icons_222222_256x240.png");
                    public static readonly string ui_icons_2e83ff_256x240_png = Url("ui-icons_2e83ff_256x240.png");
                    public static readonly string ui_icons_454545_256x240_png = Url("ui-icons_454545_256x240.png");
                    public static readonly string ui_icons_888888_256x240_png = Url("ui-icons_888888_256x240.png");
                    public static readonly string ui_icons_cd0a0a_256x240_png = Url("ui-icons_cd0a0a_256x240.png");
                }
            
                public static readonly string menu_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/menu.min.css") ? Url("menu.min.css") : Url("menu.css");
                     
                public static readonly string progressbar_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/progressbar.min.css") ? Url("progressbar.min.css") : Url("progressbar.css");
                     
                public static readonly string resizable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/resizable.min.css") ? Url("resizable.min.css") : Url("resizable.css");
                     
                public static readonly string selectable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/selectable.min.css") ? Url("selectable.min.css") : Url("selectable.css");
                     
                public static readonly string selectmenu_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/selectmenu.min.css") ? Url("selectmenu.min.css") : Url("selectmenu.css");
                     
                public static readonly string slider_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/slider.min.css") ? Url("slider.min.css") : Url("slider.css");
                     
                public static readonly string sortable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/sortable.min.css") ? Url("sortable.min.css") : Url("sortable.css");
                     
                public static readonly string spinner_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/spinner.min.css") ? Url("spinner.min.css") : Url("spinner.css");
                     
                public static readonly string tabs_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/tabs.min.css") ? Url("tabs.min.css") : Url("tabs.css");
                     
                public static readonly string theme_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/theme.min.css") ? Url("theme.min.css") : Url("theme.css");
                     
                public static readonly string tooltip_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/tooltip.min.css") ? Url("tooltip.min.css") : Url("tooltip.css");
                     
            }
        
        }
    
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class Bundles
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static partial class Scripts {}
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static partial class Styles {}
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal static class T4MVCHelpers {
    // You can change the ProcessVirtualPath method to modify the path that gets returned to the client.
    // e.g. you can prepend a domain, or append a query string:
    //      return "http://localhost" + path + "?foo=bar";
    private static string ProcessVirtualPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and must first be made absolute
        string path = VirtualPathUtility.ToAbsolute(virtualPath);
        
        // Add your own modifications here before returning the path
        return path;
    }

    // Calling ProcessVirtualPath through delegate to allow it to be replaced for unit testing
    public static Func<string, string> ProcessVirtualPath = ProcessVirtualPathDefault;

    // Calling T4Extension.TimestampString through delegate to allow it to be replaced for unit testing and other purposes
    public static Func<string, string> TimestampString = System.Web.Mvc.T4Extensions.TimestampString;

    // Logic to determine if the app is running in production or dev environment
    public static bool IsProduction() { 
        return (HttpContext.Current != null && !HttpContext.Current.IsDebuggingEnabled); 
    }
}





#endregion T4MVC
#pragma warning restore 1591, 3008, 3009


