//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProveedoresOnLine.ThirdKnowledge.WS_Inspekt {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="WS-InspektorSoap", Namespace="http://tempuri.org/SecureWebService/SecureWebService", ConfigurationName="WS_Inspekt.WSInspektorSoap")]
    public interface WSInspektorSoap {
        
        // CODEGEN: Generating message contract since message ConsultaInspektorRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SecureWebService/SecureWebService/ConsultaInspektor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.ConsultaInspektorResponse ConsultaInspektor(ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.ConsultaInspektorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SecureWebService/SecureWebService/ConsultaInspektor", ReplyAction="*")]
        System.Threading.Tasks.Task<ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.ConsultaInspektorResponse> ConsultaInspektorAsync(ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.ConsultaInspektorRequest request);
        
        // CODEGEN: Generating message contract since message ConsultaInspektorXMLRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SecureWebService/SecureWebService/ConsultaInspektorXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.ConsultaInspektorXMLResponse ConsultaInspektorXML(ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.ConsultaInspektorXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SecureWebService/SecureWebService/ConsultaInspektorXML", ReplyAction="*")]
        System.Threading.Tasks.Task<ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.ConsultaInspektorXMLResponse> ConsultaInspektorXMLAsync(ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.ConsultaInspektorXMLRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/SecureWebService/SecureWebService")]
    public partial class Autenticacion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usuarioClaveField;
        
        private string usuarioNombreField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UsuarioClave {
            get {
                return this.usuarioClaveField;
            }
            set {
                this.usuarioClaveField = value;
                this.RaisePropertyChanged("UsuarioClave");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UsuarioNombre {
            get {
                return this.usuarioNombreField;
            }
            set {
                this.usuarioNombreField = value;
                this.RaisePropertyChanged("UsuarioNombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/SecureWebService/SecureWebService")]
    public partial class Resultado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idConsultaField;
        
        private string idGrupoField;
        
        private string nombreGrupoField;
        
        private string prioridadField;
        
        private string tipoDocumentoField;
        
        private string documentoIdentidadField;
        
        private string nombreCompletoField;
        
        private string idTipoListaField;
        
        private string nombreTipoListaField;
        
        private string aliasField;
        
        private string cargoDelitoField;
        
        private string pepsField;
        
        private string zonaField;
        
        private string linkField;
        
        private string otraInformacionField;
        
        private string fechaRegistroField;
        
        private string fechaActualizacionField;
        
        private string estadoField;
        
        private string idListaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IdConsulta {
            get {
                return this.idConsultaField;
            }
            set {
                this.idConsultaField = value;
                this.RaisePropertyChanged("IdConsulta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IdGrupo {
            get {
                return this.idGrupoField;
            }
            set {
                this.idGrupoField = value;
                this.RaisePropertyChanged("IdGrupo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NombreGrupo {
            get {
                return this.nombreGrupoField;
            }
            set {
                this.nombreGrupoField = value;
                this.RaisePropertyChanged("NombreGrupo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Prioridad {
            get {
                return this.prioridadField;
            }
            set {
                this.prioridadField = value;
                this.RaisePropertyChanged("Prioridad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
                this.RaisePropertyChanged("TipoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DocumentoIdentidad {
            get {
                return this.documentoIdentidadField;
            }
            set {
                this.documentoIdentidadField = value;
                this.RaisePropertyChanged("DocumentoIdentidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string NombreCompleto {
            get {
                return this.nombreCompletoField;
            }
            set {
                this.nombreCompletoField = value;
                this.RaisePropertyChanged("NombreCompleto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string IdTipoLista {
            get {
                return this.idTipoListaField;
            }
            set {
                this.idTipoListaField = value;
                this.RaisePropertyChanged("IdTipoLista");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string NombreTipoLista {
            get {
                return this.nombreTipoListaField;
            }
            set {
                this.nombreTipoListaField = value;
                this.RaisePropertyChanged("NombreTipoLista");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
                this.RaisePropertyChanged("Alias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string CargoDelito {
            get {
                return this.cargoDelitoField;
            }
            set {
                this.cargoDelitoField = value;
                this.RaisePropertyChanged("CargoDelito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Peps {
            get {
                return this.pepsField;
            }
            set {
                this.pepsField = value;
                this.RaisePropertyChanged("Peps");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Zona {
            get {
                return this.zonaField;
            }
            set {
                this.zonaField = value;
                this.RaisePropertyChanged("Zona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
                this.RaisePropertyChanged("Link");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string OtraInformacion {
            get {
                return this.otraInformacionField;
            }
            set {
                this.otraInformacionField = value;
                this.RaisePropertyChanged("OtraInformacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string FechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
                this.RaisePropertyChanged("FechaRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string FechaActualizacion {
            get {
                return this.fechaActualizacionField;
            }
            set {
                this.fechaActualizacionField = value;
                this.RaisePropertyChanged("FechaActualizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string IdLista {
            get {
                return this.idListaField;
            }
            set {
                this.idListaField = value;
                this.RaisePropertyChanged("IdLista");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaInspektor", WrapperNamespace="http://tempuri.org/SecureWebService/SecureWebService", IsWrapped=true)]
    public partial class ConsultaInspektorRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/SecureWebService/SecureWebService")]
        public ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.Autenticacion Autenticacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/SecureWebService/SecureWebService", Order=0)]
        public string Numeiden;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/SecureWebService/SecureWebService", Order=1)]
        public string Nombre;
        
        public ConsultaInspektorRequest() {
        }
        
        public ConsultaInspektorRequest(ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.Autenticacion Autenticacion, string Numeiden, string Nombre) {
            this.Autenticacion = Autenticacion;
            this.Numeiden = Numeiden;
            this.Nombre = Nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaInspektorResponse", WrapperNamespace="http://tempuri.org/SecureWebService/SecureWebService", IsWrapped=true)]
    public partial class ConsultaInspektorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/SecureWebService/SecureWebService", Order=0)]
        public ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.Resultado[] ConsultaInspektorResult;
        
        public ConsultaInspektorResponse() {
        }
        
        public ConsultaInspektorResponse(ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.Resultado[] ConsultaInspektorResult) {
            this.ConsultaInspektorResult = ConsultaInspektorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaInspektorXML", WrapperNamespace="http://tempuri.org/SecureWebService/SecureWebService", IsWrapped=true)]
    public partial class ConsultaInspektorXMLRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/SecureWebService/SecureWebService")]
        public ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.Autenticacion Autenticacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/SecureWebService/SecureWebService", Order=0)]
        public string Numeiden;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/SecureWebService/SecureWebService", Order=1)]
        public string Nombre;
        
        public ConsultaInspektorXMLRequest() {
        }
        
        public ConsultaInspektorXMLRequest(ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.Autenticacion Autenticacion, string Numeiden, string Nombre) {
            this.Autenticacion = Autenticacion;
            this.Numeiden = Numeiden;
            this.Nombre = Nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaInspektorXMLResponse", WrapperNamespace="http://tempuri.org/SecureWebService/SecureWebService", IsWrapped=true)]
    public partial class ConsultaInspektorXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/SecureWebService/SecureWebService", Order=0)]
        public ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.Resultado[] ConsultaInspektorXMLResult;
        
        public ConsultaInspektorXMLResponse() {
        }
        
        public ConsultaInspektorXMLResponse(ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.Resultado[] ConsultaInspektorXMLResult) {
            this.ConsultaInspektorXMLResult = ConsultaInspektorXMLResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSInspektorSoapChannel : ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.WSInspektorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSInspektorSoapClient : System.ServiceModel.ClientBase<ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.WSInspektorSoap>, ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.WSInspektorSoap {
        
        public WSInspektorSoapClient() {
        }
        
        public WSInspektorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSInspektorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSInspektorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSInspektorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.ConsultaInspektorResponse ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.WSInspektorSoap.ConsultaInspektor(ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.ConsultaInspektorRequest request) {
            return base.Channel.ConsultaInspektor(request);
        }
        
        public ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.Resultado[] ConsultaInspektor(ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.Autenticacion Autenticacion, string Numeiden, string Nombre) {
            ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.ConsultaInspektorRequest inValue = new ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.ConsultaInspektorRequest();
            inValue.Autenticacion = Autenticacion;
            inValue.Numeiden = Numeiden;
            inValue.Nombre = Nombre;
            ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.ConsultaInspektorResponse retVal = ((ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.WSInspektorSoap)(this)).ConsultaInspektor(inValue);
            return retVal.ConsultaInspektorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.ConsultaInspektorResponse> ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.WSInspektorSoap.ConsultaInspektorAsync(ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.ConsultaInspektorRequest request) {
            return base.Channel.ConsultaInspektorAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.ConsultaInspektorResponse> ConsultaInspektorAsync(ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.Autenticacion Autenticacion, string Numeiden, string Nombre) {
            ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.ConsultaInspektorRequest inValue = new ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.ConsultaInspektorRequest();
            inValue.Autenticacion = Autenticacion;
            inValue.Numeiden = Numeiden;
            inValue.Nombre = Nombre;
            return ((ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.WSInspektorSoap)(this)).ConsultaInspektorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.ConsultaInspektorXMLResponse ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.WSInspektorSoap.ConsultaInspektorXML(ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.ConsultaInspektorXMLRequest request) {
            return base.Channel.ConsultaInspektorXML(request);
        }
        
        public ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.Resultado[] ConsultaInspektorXML(ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.Autenticacion Autenticacion, string Numeiden, string Nombre) {
            ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.ConsultaInspektorXMLRequest inValue = new ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.ConsultaInspektorXMLRequest();
            inValue.Autenticacion = Autenticacion;
            inValue.Numeiden = Numeiden;
            inValue.Nombre = Nombre;
            ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.ConsultaInspektorXMLResponse retVal = ((ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.WSInspektorSoap)(this)).ConsultaInspektorXML(inValue);
            return retVal.ConsultaInspektorXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.ConsultaInspektorXMLResponse> ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.WSInspektorSoap.ConsultaInspektorXMLAsync(ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.ConsultaInspektorXMLRequest request) {
            return base.Channel.ConsultaInspektorXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.ConsultaInspektorXMLResponse> ConsultaInspektorXMLAsync(ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.Autenticacion Autenticacion, string Numeiden, string Nombre) {
            ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.ConsultaInspektorXMLRequest inValue = new ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.ConsultaInspektorXMLRequest();
            inValue.Autenticacion = Autenticacion;
            inValue.Numeiden = Numeiden;
            inValue.Nombre = Nombre;
            return ((ProveedoresOnLine.ThirdKnowledge.WS_Inspekt.WSInspektorSoap)(this)).ConsultaInspektorXMLAsync(inValue);
        }
    }
}
