//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketPlace.Web.WS_Inspector {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="WS-InspektorSoap", Namespace="http://tempuri.org/SecureWebService/SecureWebService", ConfigurationName="WS_Inspector.WSInspektorSoap")]
    public interface WSInspektorSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje ConsultaInspektorRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SecureWebService/SecureWebService/ConsultaInspektor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MarketPlace.Web.WS_Inspector.ConsultaInspektorResponse ConsultaInspektor(MarketPlace.Web.WS_Inspector.ConsultaInspektorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SecureWebService/SecureWebService/ConsultaInspektor", ReplyAction="*")]
        System.Threading.Tasks.Task<MarketPlace.Web.WS_Inspector.ConsultaInspektorResponse> ConsultaInspektorAsync(MarketPlace.Web.WS_Inspector.ConsultaInspektorRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/SecureWebService/SecureWebService")]
    public partial class Autenticacion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usuarioClaveField;
        
        private string usuarioNombreField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UsuarioClave {
            get {
                return this.usuarioClaveField;
            }
            set {
                this.usuarioClaveField = value;
                this.RaisePropertyChanged("UsuarioClave");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UsuarioNombre {
            get {
                return this.usuarioNombreField;
            }
            set {
                this.usuarioNombreField = value;
                this.RaisePropertyChanged("UsuarioNombre");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaInspektor", WrapperNamespace="http://tempuri.org/SecureWebService/SecureWebService", IsWrapped=true)]
    public partial class ConsultaInspektorRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/SecureWebService/SecureWebService")]
        public MarketPlace.Web.WS_Inspector.Autenticacion Autenticacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/SecureWebService/SecureWebService", Order=0)]
        public string Numeiden;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/SecureWebService/SecureWebService", Order=1)]
        public string Nombre;
        
        public ConsultaInspektorRequest() {
        }
        
        public ConsultaInspektorRequest(MarketPlace.Web.WS_Inspector.Autenticacion Autenticacion, string Numeiden, string Nombre) {
            this.Autenticacion = Autenticacion;
            this.Numeiden = Numeiden;
            this.Nombre = Nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaInspektorResponse", WrapperNamespace="http://tempuri.org/SecureWebService/SecureWebService", IsWrapped=true)]
    public partial class ConsultaInspektorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/SecureWebService/SecureWebService", Order=0)]
        public string ConsultaInspektorResult;
        
        public ConsultaInspektorResponse() {
        }
        
        public ConsultaInspektorResponse(string ConsultaInspektorResult) {
            this.ConsultaInspektorResult = ConsultaInspektorResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSInspektorSoapChannel : MarketPlace.Web.WS_Inspector.WSInspektorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSInspektorSoapClient : System.ServiceModel.ClientBase<MarketPlace.Web.WS_Inspector.WSInspektorSoap>, MarketPlace.Web.WS_Inspector.WSInspektorSoap {
        
        public WSInspektorSoapClient() {
        }
        
        public WSInspektorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSInspektorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSInspektorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSInspektorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MarketPlace.Web.WS_Inspector.ConsultaInspektorResponse MarketPlace.Web.WS_Inspector.WSInspektorSoap.ConsultaInspektor(MarketPlace.Web.WS_Inspector.ConsultaInspektorRequest request) {
            return base.Channel.ConsultaInspektor(request);
        }
        
        public string ConsultaInspektor(MarketPlace.Web.WS_Inspector.Autenticacion Autenticacion, string Numeiden, string Nombre) {
            MarketPlace.Web.WS_Inspector.ConsultaInspektorRequest inValue = new MarketPlace.Web.WS_Inspector.ConsultaInspektorRequest();
            inValue.Autenticacion = Autenticacion;
            inValue.Numeiden = Numeiden;
            inValue.Nombre = Nombre;
            MarketPlace.Web.WS_Inspector.ConsultaInspektorResponse retVal = ((MarketPlace.Web.WS_Inspector.WSInspektorSoap)(this)).ConsultaInspektor(inValue);
            return retVal.ConsultaInspektorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MarketPlace.Web.WS_Inspector.ConsultaInspektorResponse> MarketPlace.Web.WS_Inspector.WSInspektorSoap.ConsultaInspektorAsync(MarketPlace.Web.WS_Inspector.ConsultaInspektorRequest request) {
            return base.Channel.ConsultaInspektorAsync(request);
        }
        
        public System.Threading.Tasks.Task<MarketPlace.Web.WS_Inspector.ConsultaInspektorResponse> ConsultaInspektorAsync(MarketPlace.Web.WS_Inspector.Autenticacion Autenticacion, string Numeiden, string Nombre) {
            MarketPlace.Web.WS_Inspector.ConsultaInspektorRequest inValue = new MarketPlace.Web.WS_Inspector.ConsultaInspektorRequest();
            inValue.Autenticacion = Autenticacion;
            inValue.Numeiden = Numeiden;
            inValue.Nombre = Nombre;
            return ((MarketPlace.Web.WS_Inspector.WSInspektorSoap)(this)).ConsultaInspektorAsync(inValue);
        }
    }
}
